server:
  port: 10000

spring:
  application:
    name: server

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka/
      # defaultZone: http://peer1:8081/eureka/,http://peer2:8082/eureka/,http://peer3:8083/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"