server:
  port: 9090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 是否可以通过其他服务的serviceId来转发到具体的服务实例。默认为false
          # 为true，自动创建路由，路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问
          enabled: true
          # 微服务应用名小写访问
          lowerCaseServiceId: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka/
      # defaultZone: http://peer1:8081/eureka/,http://peer2:8082/eureka/,http://peer3:8083/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"